CREATE DATABASE IF NOT EXISTS u_lasalle CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE u_lasalle;

CREATE TABLE IF NOT EXISTS contacts (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  full_name VARCHAR(80) NOT NULL,
  email VARCHAR(120) NOT NULL,
  subject VARCHAR(120) NOT NULL,
  message TEXT NOT NULL,
  program VARCHAR(80) NULL,
  phone VARCHAR(25) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
